ordenes/urls.py
from django.urls import path, include
from . import views

from .views import      OrdenListView\
                    ,   OrdenDetailView\
                    ,   OrdenCreateView\
                    ,   OrdenUpdateView\
                    ,   ComercioListView\
                    ,   ComercioDetailView\
                    ,   ComercioCreateView\
                    ,   ComercioUpdateView\
                    ,   EmpleadoListView\
                    ,   EmpleadoDetailView\
                    ,   EmpleadoCreateView\
                    ,   EmpleadoUpdateView\
                    ,   busca\
                    ,   CrearOrden\
                    ,   Imprimir\
                    ,   ImprimirUltima\
                    ,   MargenEmpleado\
                    ,   OrdenEmpleado\
                    ,   CompraEmpleado\
                    ,   Buscaempleado
                    
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.auth.decorators import login_required

app_name = "ordenes"

urlpatterns = [
    path("", login_required(OrdenListView.as_view()), name="orden_all"),
    path("create/<int:empleado>/<int:comercio>/<margen>", CrearOrden,name="create_orden"),
    path('orden/create',OrdenCreateView.as_view(), name="orden_create"),
    path("<int:pk>/orden/detail/", OrdenDetailView.as_view(), name="orden_detail"),
    path("<int:pk>/orden/update/", OrdenUpdateView.as_view(), name="orden_update"),
    path("comercio", login_required(ComercioListView.as_view()), name="comercio_all"),
    path("comercio/create/", ComercioCreateView.as_view(), name="comercio_create"),
    path("<int:pk>/comercio/detail/", ComercioDetailView.as_view(), name="comercio_detail"),
    path("<int:pk>/comercio/update/", ComercioUpdateView.as_view(), name="comercio_update"),
    #path("empleado", login_required(EmpleadoListView.as_view()), name="empleado_all"),
    path("empleado", login_required(Buscaempleado), name="empleado_all"),
    path("empleado/create/", EmpleadoCreateView.as_view(), name="empleado_create"),
    path("create/preconsulta/", busca, name="preconsulta"),
    path("<int:pk>/empleado/detail/", EmpleadoDetailView.as_view(), name="empleado_detail"),
    path("<int:pk>/empleado/update/", EmpleadoUpdateView.as_view(), name="empleado_update"),
    path("<int:pk>/export/", Imprimir.as_view(), name="export_pdf"),
    path("export/", ImprimirUltima.as_view(), name="imprime_last"),
    path("consulta/margen/", MargenEmpleado, name="consulta_saldo"),
    path("consulta/orden/", OrdenEmpleado, name="consulta_orden"),
    path("consulta/compras/", CompraEmpleado, name="consulta_compras"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


stia/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import Landing , About, Consultas
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Landing.as_view(),name='landing'),
    path('consultas',Consultas.as_view(),name='consultas'),
    path('about',About.as_view(),name='about'),
    path('ordenes/', include('ordenes.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

ordenes/models.py
from django.db import models

# Create your models here.
class Comercio(models.Model):
    id = models.AutoField(primary_key=True)
    comercio = models.CharField(max_length=30,verbose_name='Comercio',null=False) # VERBOSE nombre de las filas en superususario #
    titular = models.CharField(max_length=30,verbose_name='Titular de Comercio',null=False)
    activo = models.BooleanField(verbose_name='Activo',null=True,default=True)

    def __str__(self):
        fila = self.comercio
        return fila
    
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]
    
    class Meta:
        verbose_name = 'Comercio'
        verbose_name_plural = 'Comercios'
        db_table = 'comercio'
        ordering = ['comercio']
                

class Empleado(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30,verbose_name="Nombre y Apellido",null=False)
    legajo = models.IntegerField(verbose_name='Legajo N°',null=False)
    dni = models.IntegerField(verbose_name='DNI',null=False)
    activo = models.BooleanField(verbose_name='Activo',null=True,default=True)

    # ESTO SE MUESTRA EN EL ADMIN SUPERUSUARIO #
    def __str__(self):
        fila = self.nombre
        return fila

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]]

    class Meta:
        verbose_name='empleado'
        verbose_name_plural='empleados'
        db_table='empleado'
        ordering = ['nombre']

class Orden(models.Model):
    id = models.AutoField(primary_key=True)
    empleado = models.ForeignKey(Empleado,on_delete=models.CASCADE,null=False, blank=False)
    comercio = models.ForeignKey(Comercio,on_delete=models.CASCADE,null=False, blank=False)
    importe = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Total Compra',null=False)
    cuotas = models.IntegerField(verbose_name='Cuotas',null=False)
    valorcuota = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Valor de Cuota',null=False)
    fecha = models.DateField(verbose_name='Fecha de Compra', auto_now=True,null=False)
    
    def __str__(self):
        fila = "Empleado: " + str(self.empleado) + " - " + " Comercio: " + str(self.comercio) + " Importe: " + str(self.importe) + " Cuotas: " + str(self.cuotas)+ " Valor de Cuota: " + str(self.valorcuota) + " fecha y hora: " + str(self.fecha)
        return fila
    
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

    class Meta:
        verbose_name='orden'
        verbose_name_plural='ordenes'
        db_table = 'ordenes_orden'
    

class Margen(models.Model):
    id=models.AutoField(primary_key=True)
    margen = models.IntegerField(verbose_name='Margen',null=False)

    def __str__(self):
        fila = "Margen: " + str(self.margen)
        return fila

    class Meta:
        verbose_name='margen'
        verbose_name_plural='margenes'
        db_table = 'margen'

ordenes/views.py
from typing import Any
from django.db import models
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from .models import Orden, Comercio, Empleado, Margen
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView

import datetime
from django.db.models import Q

from django.contrib import messages

from django.template.loader import render_to_string
from weasyprint import HTML

from django.http import HttpResponseRedirect
from datetime import date, timedelta



# Create your views here.
#  O R D E N E S #

class OrdenBaseView(View):
    login_url = "/login/"
    redirect_field_name = "landing"
    template_name = "orden.html"
    model         = Orden
    fields        = "__all__"
    success_url   = reverse_lazy('ordenes:orden_all')

    def get_queryset(self):
        return Orden.objects.all().order_by('-id')[:8]
    

class OrdenListView(OrdenBaseView,ListView):
    '''ESTO ME PERMITE CREAR UNA VISTA CON LOS ORDENES'''

class OrdenDetailView(OrdenBaseView,ListView):
    template_name = 'orden_template.html'

class OrdenCreateView(CreateView):
    empleados = Empleado.objects.all()
    comercios = Comercio.objects.all()
    margen =  Margen.objects.all()[:1]
    template_name = 'orden_create.html'
    extra_context = {"tipo": "Crear Orden",'empleados':empleados,
                     'comercios':comercios,'limite':margen}
  
    success_url   = reverse_lazy('ordenes:orden_all')
    


   


def CrearOrden(request,empleado,comercio,margen):
    disponible=margen

    if request.method == 'POST':
        
        emp = request.POST.get('empleado')
        empleado = Empleado.objects.get(pk=emp)
        com = request.POST.get('comercio')
        comercio = Comercio.objects.get(pk=com)
        imp = request.POST.get('importe')
        cuo = request.POST.get('cuotas')
        fecha = request.POST.get('fecha')
        print(type(cuo))
        print(type(imp))
        valorcuota = int(imp)/int(cuo)
        nuevaorden = Orden(empleado= empleado, comercio= comercio, importe= imp, cuotas=cuo ,valorcuota=valorcuota,fecha=fecha)
        nuevaorden.save()
        #ultimaorden= Orden.objects.last()
        #idorden= ultimaorden.id
        #return redirect('ordenes:imprime_last')
        return redirect('ordenes:orden_all')
    
    if request.method == 'GET':
        orden = Orden.objects.all()
        comercios = Comercio.objects.filter(Q(id=comercio))
        empleados = Empleado.objects.filter(Q(id=empleado))
        empleado= empleado
        comercio = comercio
        margen=margen
        messages.success(request,'Empleado y Comercio agregado con exito')
        return render(request, 'orden_create.html',{'empleado':empleado,'margen':margen,
                'comercios':comercios,'comercio':comercio,'orden':orden,'empleados':empleados
            })





class OrdenUpdateView(OrdenBaseView,UpdateView):
    template_name = 'orden_create.html'
    extra_context = {"tipo": "Actualizar Orden"}

# C O M E R C I O S #
class ComercioBaseView(View):
    template_name = "comercio.html"
    model         = Comercio
    fields        = "__all__"
    success_url   = reverse_lazy('ordenes:comercio_all')

class ComercioListView(ComercioBaseView, ListView):
    '''ESTO ME PERMITE CREAR UNA VISTA CON LOS COMERCIOS'''

class ComercioDetailView(ComercioBaseView, ListView):
    template_name = 'comercio_template.html'

class ComercioCreateView(ComercioBaseView, CreateView):
    template_name = 'comercio_create.html'
    extra_context = {"tipo": "Crear Comercio"}

class ComercioUpdateView(ComercioBaseView, UpdateView):
    template_name = 'comercio_update.html'
    extra_context = {"tipo": "Actualizar Comercio"}

# E M P L E A D O S #

class EmpleadoBaseView(View):
    template_name = "empleado.html"
    model         = Empleado
    fields        = "__all__"
    success_url   = reverse_lazy('ordenes:empleado_all')

class EmpleadoListView(EmpleadoBaseView, ListView):
    '''ESTO ME PERMITE CREAR UNA VISTA CON LOS EMPLEADOS'''


class EmpleadoDetailView(EmpleadoBaseView, ListView):
    template_name = 'empleado_template.html'
    

class EmpleadoCreateView(EmpleadoBaseView, CreateView):
    template_name = 'empleado_create.html'
    extra_context = {"tipo": "Crear Empleado"}

class EmpleadoUpdateView(EmpleadoBaseView, UpdateView):
    template_name = 'empleado_update.html'
    extra_context = {"tipo": "Actualizar Empleado"}

#def nuevaorden(request):
#    resultado = Empleado.objects.all()
#    resultado2 = Comercio.objects.all()
#    return render(request,"orden_create.html",{"nombres":resultado,"comercios":resultado2})


def busca(request):
    
        busqueda = request.POST.get("buscarempleado")
        busqueda2 = request.POST.get("buscarcomercio")
        empleados =Empleado.objects.all().filter(activo=True)
        comercios =Comercio.objects.all().filter(activo=True)
        empleado =Empleado.objects.all()
        ordenes=Orden.objects.all()
        margen = Margen.objects.all()[:1]
        hoy = datetime.date.today()
        mes=hoy.month
        if mes<10:
            mes='0'+str(mes)
        fechahoy = int(str(hoy.year)+mes)
        valorcuota=0
        margendisponible=0
        limite=0
        for i in margen:
            margendisponible = margendisponible +i.margen
            limite = limite +i.margen

        if busqueda and busqueda2:
            
            empleado = Empleado.objects.filter(Q(id__icontains = busqueda))
            comercio = Comercio.objects.filter(Q(id__icontains = busqueda2))
            ordenes = Orden.objects.filter(Q(empleado_id=busqueda))
            saldo = 0
            for orden in ordenes:
                valorcuota = orden.importe/orden.cuotas
                if orden.cuotas > 1:
                    for i in range(1,orden.cuotas):
                        print(i)
                        mes1=orden.fecha.month
                        if mes1<10:
                            mes1='0'+str(mes1)
                        fecha = int(str(hoy.year)+mes1)
                        if fecha >= fechahoy:
                            saldo += valorcuota
                else:
                    saldo += valorcuota
            margendisponible = margendisponible - saldo
            return render(request, 'preconsulta.html',{'comercio':comercio,
                        'comercios':comercios,'empleado':empleado,
                        'empleados':empleados,'margen':'{0:.2f}'.format(margendisponible),
                        'limite':limite})
            
            #return HttpResponse({'margen':'{0:.2f}'.format(margendisponible)})
                        
        else:
            return render(request, 'preconsulta.html',{'comercios':comercios,
                        'empleados':empleados,})

# MARGEN EMPLEADO
def MargenEmpleado(request):
        busqueda = request.POST.get("margenempleado")
        fecha1 = date.today()-timedelta(days=60)
        fecha2 = date.today()
        empleados =Empleado.objects.all().filter(activo=True)
        empleado =Empleado.objects.all()
        ordenes=Orden.objects.all()
        margen = Margen.objects.all()[:1]
        hoy = datetime.date.today()
        mes=hoy.month
        if mes<10:
            mes='0'+str(mes)
        fechahoy = int(str(hoy.year)+mes)
        valorcuota=0
        margendisponible=0
        limite=0

        for i in margen:
            margendisponible = margendisponible +i.margen
            limite = limite +i.margen
        if busqueda:
            empleado = Empleado.objects.filter(Q(id__icontains = busqueda))
            ordenes = Orden.objects.filter(Q(empleado_id=busqueda))
            saldo = 0
            for orden in ordenes:
                valorcuota = orden.importe/orden.cuotas
                if orden.cuotas > 1:
                    for i in range(1,orden.cuotas):
                        mes1=orden.fecha.month
                        if mes1<10:
                            mes1='0'+str(mes1)
                        fecha = int(str(orden.fecha.year)+mes1)
                        if fecha >= fechahoy:
                            saldo += valorcuota
                else:
                    saldo += valorcuota
            margendisponible = margendisponible - saldo
            
            ordenes =Orden.objects.filter(Q(empleado_id=busqueda)).filter(fecha__range=(fecha1,fecha2)).order_by('-id')
            return render(request, 'consulta_margen.html',{'empleado':empleado,
                        'empleados':empleados,'margen':'{0:.2f}'.format(margendisponible),
                        'limite':limite,'orden':ordenes})
                       
        else:
            return render(request, 'consulta_margen.html',{'empleados':empleados,})

def CompraEmpleado(request):
        busqueda = request.POST.get("empleado")
        fecha1 = request.POST.get("fecha1")
        fecha2 = request.POST.get("fecha2")
        empleados =Empleado.objects.all()

        ordenes=Orden.objects.all()

        if busqueda:
            empleado = Empleado.objects.filter(Q(id__icontains = busqueda))
            ordenes =Orden.objects.filter(Q(empleado_id=busqueda)).filter(fecha__range=(fecha1,fecha2)).order_by('-id')
            return render(request, 'consulta_compras.html',{
                        'empleados':empleados,'orden':ordenes})
                       
        else:
            return render(request, 'consulta_compras.html',{'empleados':empleados,})

def OrdenEmpleado(request):
        busqueda = request.POST.get("ordenempleado")

ordenes/templates/comercio.html
{% extends "base.html" %}
{% block content %}


<div class="<div class="table-responsive">
    <h4  style="text-align: center;">COMERCIOS</h4>
    <div class="label-input"> 
        <a href="{% url 'ordenes:comercio_create' %}" class="btn btn-info">Crear Nuevo Comercio</a>    
    </div>
    <table class="table table-primary">
        <thead>
            <tr>
                <th scope="col"ID</th>
                <th scope="col">COMERCIO</th>
                <th scope="col">TITULAR</th>
                <th scope="col">ACTIVO</th>
                <th scope="col"></th>
            </tr>
        </thead>
        {% for comercio in comercio_list %}
        <tbody>
            <tr>
                {% if comercio.activo %}
                    <td scope="row">{{comercio.id}}</td>
                    <td>{{comercio.comercio}}</td>
                    <td>{{comercio.titular}}</td>
                    <td>Activo</td>
                {% else %}    
                    <td scope="row" class="text-secondary">{{comercio.id}}</td>
                    <td class="text-secondary">{{comercio.comercio}}</td>
                    <td class="text-secondary">{{comercio.titular}}</td>
                    <td class="text-secondary">Inactivo</td>
                {% endif %}
                <td>                                
                    |
                    <a href="{% url 'ordenes:comercio_update' comercio.id %}" class="btn btn-success">Editar</a>
                    |
                </td>
            <tr>
        </tbody>
        {% endfor %}
    </table>
</div>
{% endblock %}

ordenes/templates/comercio_update.html
{% extends "base.html" %}
{% block content %}

<div class="card">
    <div class="card-header">
        <h4  style="text-align: center;">EDITAR COMERCIO</h4>
    </div>
    <div class="card-body">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!--<div>{{form.as_p}}-->
            <div class="label-input">
                <p>
                    <label for="id_comercio">Nombre del Comercio:</label>
                    <input type="text" name="comercio" maxlength="30" required="True" id="id_comercio"
                        value="{{ comercio.comercio }}" class="form-control" style="width: 400px;"/>
                </p>
                <p>
                    <label for="id_titular">Titular del Comercio:</label>
                    <input type="text" name="titular" maxlength="30" required="True" id="id_titular"
                        value="{{ comercio.titular }}" class="form-control" style="width: 400px;"/>
                </p>
                <p>
                    <label for="id_activo">Activo:</label>
                    <select name="activo" id="id_activo" class="form-control">
                        {% if comercio.activo %}
                        <option value="True" selected >SI</option>
                        <option value="False" >NO</option>
                        {% else %}
                        <option value="True" >SI</option>
                        <option value="False" selected >NO</option>
                        {% endif %}
                    </select>
                </p>
            </div>
            <div class="label-input">
                <input type="submit" value="{{ tipo }}" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
{% endblock %}

ordenes/templates/empleado.html
{% extends "base.html" %}
{% block content %}

<div class="<div class=" table-responsive">
  <h4 style="text-align: center;">EMPLEADOS</h4>
  <div class="label-input">
    <a href="{% url 'ordenes:empleado_create' %}" class="btn btn-info">Agregar Nuevo Empleado</a>
  </div>

  <table class="table table-primary">
    <thead>
      <tr>
        <th scope="col" ID</th>
        <th scope="col">NOMBRE</th>
        <th scope="col">LEGAJO</th>
        <th scope="col">DNI</th>
        <th scope="col">ACTIVO</th>
        <th></th>
      </tr>
    </thead>
    {% for empleado in empleado_list %}
    <tbody>
      <tr>
        {% if empleado.activo %}
        <td scope="row">{{empleado.id}}</td>
        <td>{{empleado.nombre}}</td>
        <td>{{empleado.legajo}}</td>
        <td>{{empleado.dni}}</td>
        <td>Activo</td>
        {% else %}
        <td scope="row" class="text-secondary">{{empleado.id}}</td>
        <td class="text-secondary">{{empleado.nombre}}</td>
        <td class="text-secondary">{{empleado.legajo}}</td>
        <td class="text-secondary">{{empleado.dni}}</td>
        <td class="text-secondary">Inactivo</td>
        {% endif %}
        <td>
          |
          <a href="{% url 'ordenes:empleado_update' empleado.id %}" class="btn btn-success">Editar</a>
          |
        </td>
      <tr>
    </tbody>
    {% endfor %}
  </table>
</div>

<div class="card-body">
  <form class="card-body" method="POST">
    {% csrf_token %}
    <div class="label-input">
      <p>
        <input type="text" placeholder="Buscar..." list="buscar" name="updateempleado" maxlength="30" required="True"
          class="form-control" style="width:100px" />
        <datalist id="buscar">
          {% for empleado in empleado_list %}
          <option value="{{ empleado.id }}">{{ empleado.nombre }} {{ empleado.legajo }} {{ empleado.dni }}</option>
          {% endfor %}
        </datalist>
      </p>

    </div>
    <div class="label-input">
      <input type="submit" value="Buscar" class="btn btn-success" style="height: 40px;" />
    </div>
    {% if empleado %}
    <table class="table table-primary">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">NOMBRE</th>
          <th scope="col">LEGAJO</th>
          <th scope="col">DNI</th>
          <th scope="col">ACTIVO</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          {% for empleado in empleado %}
          {% if empleado.activo %}
          <td>{{ empleado.id }}</td>
          <td>{{ empleado.nombre }}</td>
          <td>{{ empleado.legajo }}</td>
          <td>{{ empleado.dni }}</td>
          <td>Activo</td>
          {% else %}
          <td class="text-secondary">{{ empleado.id }}</td>
          <td class="text-secondary">{{ empleado.nombre }}</td>
          <td class="text-secondary">{{ empleado.legajo }}</td>
          <td class="text-secondary">{{ empleado.dni }}</td>
          <td class="text-secondary">Inactivo</td>
          {% endif %}
          <td>
            |
            <a href="{% url 'ordenes:empleado_update' empleado.id %}" class="btn btn-success">Editar</a>
            |
          </td>

          {% endfor %}
        <tr>
      </tbody>

    </table>

    {% endif %}
</div>
</form>

</div>


{% endblock %}

ordenes/templates/empleado2.html
{% extends "base.html" %}
{% block content %}



<div class="<div class="table-responsive">
    <h4  style="text-align: center;">EMPLEADOS</h4>
    <div class="label-input">
        <a href="{% url 'ordenes:empleado_create' %}" class="btn btn-info">Agregar Nuevo Empleado</a>
    </div>
    
    <table class="table table-primary">
        <thead>
            <tr>
                <th scope="col"ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">LEGAJO</th>
                <th scope="col">DNI</th>
                <th scope="col">ACTIVO</th>
                <th></th>
            </tr>
        </thead>
        {% for empleado in empleado_list %}
        <tbody>
            <tr>
                {% if empleado.activo %}
                <td scope="row">{{empleado.id}}</td>
                <td>{{empleado.nombre}}</td>
                <td>{{empleado.legajo}}</td>
                <td>{{empleado.dni}}</td>
                <td>Activo</td>
                {% else %}
                <td scope="row" class="text-secondary">{{empleado.id}}</td>
                <td class="text-secondary">{{empleado.nombre}}</td>
                <td class="text-secondary">{{empleado.legajo}}</td>
                <td class="text-secondary">{{empleado.dni}}</td>
                <td class="text-secondary">Inactivo</td>
                {% endif %}
                <td>                                
                    |
                    <a href="{% url 'ordenes:empleado_update' empleado.id %}" class="btn btn-success">Editar</a>
                    |
                </td>
            <tr>
        </tbody>
        {% endfor %}
    </table>
</div>
<!-- BUSCA EMPLEADO -->
<div class="card-body">
    <form class="card-body" method="POST">
      {% csrf_token %}
      <div class="label-input">
        <p>
          <label for="id_empleado">EMPLEADO:</label>
  
          <input type="text" placeholder="Buscar..." list="buscar" name="updateaempleado" maxlength="30" required="True"
            class="form-control" style="width:100px" />
          <datalist id="buscar">
            {% for empleado in empleado_list %}
            <option value="{{ empleado.id }}">{{ empleado.nombre }} {{ empleado.legajo }} {{ empleado.dni }}</option>
            {% endfor %}
          </datalist>
        </p>
      </div>
      <div class="label-input">
        <input type="submit" value="Buscar" class="btn btn-success" style="height: 40px;" />
      </div>
      {% if empleado %}
      <table class="table table-primary">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">NOMBRE</th>
            <th scope="col">LEGAJO</th>
            <th scope="col">DNI</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            {% for empleado in empleado %}
            <td>{{ empleado.id }}</td>
            <td>{{ empleado.nombre }}</td>
            <td>{{ empleado.legajo }}</td>
            <td>{{ empleado.dni }}</td>
            {% endfor %}
          <tr>
        </tbody>
      </table>
      {% endif %}
    </form>
  
</div>

{% endblock %}

ordenes/templates/empleado_create.html
{% extends "base.html" %}
{% block content %}

<div class="card">
    <div class="card-header">
        <h4  style="text-align: center;">AGREGA EMPLEADO</h4>
    </div>
    <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <!--<div>{{form.as_p}}-->
                <div class="label-input">
                <p>
                    <label for="id_nombre">Apellido y Nombre:</label>
                    <input type="text" name="nombre" maxlength="30" required="True" id="id_nombre" value="{{ empleado.nombre }}"
                    class="form-control" style="width: 400px;"/>
                </p>
                <p>
                    <label for="id_legajo">Número de Legajo:</label>
                    <input type="number" name="legajo" required="True" id="id_legajo" value="{{ empleado.legajo }}"
                    class="form-control" style="width: 200px;"/>
                </p>
                <p>
                    <label for="id_dni">Número de DNI:</label>
                    <input type="number" name="dni" required="True" id="id_dni" value="{{ empleado.dni }}"
                    class="form-control" style="width: 200px;"/>
                </p>
                </div>
                <div class="label-input">
                <input type="submit" value="{{ tipo }}" class="btn btn-success" />
                </div>
            </form>
    </div>
    <div class="card-footer text-muted">

    </div>
</div>
{% endblock %}

ordenes/templates/empleado_update.html
{% extends "base.html" %}
{% block content %}

<div class="card">
    <div class="card-header">
        <h4  style="text-align: center;">ACTUALIZA DATOS DEL EMPLEADO</h4>
    </div>
    <div class="card-body">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!--<div>{{form.as_p}}-->
            <div class="label-input">
                <p>
                    <label for="id_nombre">Apellido y Nombre:</label>
                    <input type="text" name="nombre" maxlength="30" required="True" id="id_nombre"
                        value="{{ empleado.nombre }}" class="form-control" style="width: 400px;" />
                </p>
                <p>
                    <label for="id_legajo">Número de Legajo:</label>
                    <input type="number" name="legajo" required="True" id="id_legajo" value="{{ empleado.legajo }}"
                        class="form-control" style="width: 200px;" />
                </p>
                <p>
                    <label for="id_dni">Número de DNI:</label>
                    <input type="number" name="dni" required="True" id="id_dni" value="{{ empleado.dni }}"
                        class="form-control" style="width: 200px;" />
                </p>
                <p>
                    <label for="id_activo">Activo:</label>
                    <select name="activo" id="id_activo" class="form-control">
                        {% if empleado.activo %}
                        <option value="True" selected >SI</option>
                        <option value="False" >NO</option>
                        {% else %}
                        <option value="True" >SI</option>
                        <option value="False" selected >NO</option>
                        {% endif %}
                    </select>
                </p>
            </div>
            <div class="label-input">
                <input type="submit" value="{{ tipo }}" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
{% endblock %}