ordenes/urls.py
from django.urls import path, include
from . import views

from .views import      OrdenListView\
                    ,   OrdenDetailView\
                    ,   OrdenCreateView\
                    ,   OrdenUpdateView\
                    ,   ComercioListView\
                    ,   ComercioDetailView\
                    ,   ComercioCreateView\
                    ,   ComercioUpdateView\
                    ,   EmpleadoListView\
                    ,   EmpleadoDetailView\
                    ,   EmpleadoCreateView\
                    ,   EmpleadoUpdateView\
                    ,   busca\
                    ,   CrearOrden\
                    ,   Imprimir\
                    ,   ImprimirUltima\
                    ,   MargenEmpleado\
                    ,   OrdenEmpleado\
                    ,   CompraEmpleado\
                    ,   Buscaempleado
                    
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.auth.decorators import login_required

app_name = "ordenes"

urlpatterns = [
    path("", login_required(OrdenListView.as_view()), name="orden_all"),
    path("create/<int:empleado>/<int:comercio>/<margen>", CrearOrden,name="create_orden"),
    path('orden/create',OrdenCreateView.as_view(), name="orden_create"),
    path("<int:pk>/orden/detail/", OrdenDetailView.as_view(), name="orden_detail"),
    path("<int:pk>/orden/update/", OrdenUpdateView.as_view(), name="orden_update"),
    path("comercio", login_required(ComercioListView.as_view()), name="comercio_all"),
    path("comercio/create/", ComercioCreateView.as_view(), name="comercio_create"),
    path("<int:pk>/comercio/detail/", ComercioDetailView.as_view(), name="comercio_detail"),
    path("<int:pk>/comercio/update/", ComercioUpdateView.as_view(), name="comercio_update"),
    #path("empleado", login_required(EmpleadoListView.as_view()), name="empleado_all"),
    path("empleado", login_required(Buscaempleado), name="empleado_all"),
    path("empleado/create/", EmpleadoCreateView.as_view(), name="empleado_create"),
    path("create/preconsulta/", busca, name="preconsulta"),
    path("<int:pk>/empleado/detail/", EmpleadoDetailView.as_view(), name="empleado_detail"),
    path("<int:pk>/empleado/update/", EmpleadoUpdateView.as_view(), name="empleado_update"),
    path("<int:pk>/export/", Imprimir.as_view(), name="export_pdf"),
    path("export/", ImprimirUltima.as_view(), name="imprime_last"),
    path("consulta/margen/", MargenEmpleado, name="consulta_saldo"),
    path("consulta/orden/", OrdenEmpleado, name="consulta_orden"),
    path("consulta/compras/", CompraEmpleado, name="consulta_compras"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


stia/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import Landing , About, Consultas
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Landing.as_view(),name='landing'),
    path('consultas',Consultas.as_view(),name='consultas'),
    path('about',About.as_view(),name='about'),
    path('ordenes/', include('ordenes.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous">
        </script>
    <title>STIA ORDENES</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="shortcut icon" href="/static/media/img/logo_stia.png" type="image/x-icon">


</head>

<body>
    <header>
          <nav class="navbar navbar-expand-lg  bg-primary">
                            <div class="container-fluid">
                                <div class="logonav">
                                    <img src="/static/media/img/logo_stia.png" alt="">
                                </div>
                                <a class="navbar-brand text-white" href="{% url 'landing' %}">STIA ORDENES</a>
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                        <li class="nav-item">
                                            <a class="nav-link active text-white" aria-current="page" href="{% url 'landing' %}">INICIO</a>
                                        </li>
                                        <li class="nav-item dropdown">
                                            {% if request.user.is_authenticated %}
                                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                                data-bs-toggle="dropdown" aria-expanded="false">
                                                CONSULTAS
                                            </a>
                                            {% endif %}
                                            <ul class="dropdown-menu bg-primary">
                                                <li><a class="dropdown-item text-white"
                                                        href="{% url 'ordenes:consulta_saldo' %}">CONSULTA DE MARGEN</a>
                                                </li>
                                                <li><a class="dropdown-item text-white" href="{% url 'ordenes:consulta_orden' %}">CONSULTA DE ORDEN</a></li>
                                                <li><a class="dropdown-item text-white" href="{% url 'ordenes:consulta_compras' %}">CONSULTA DE COMPRAS</a></li>
                                            </ul>
                                        </li>
                                        <li class="nav-item">
                                            {% if request.user.is_authenticated %}
                                            <a class="nav-link text-white" href="{% url 'ordenes:orden_all' %}">ORDENES</a>
                                            {% endif %}
                                        </li>
                                        <li class="nav-item">
                                            {% if request.user.is_authenticated %}
                                            <a class="nav-link text-white" href="{% url 'ordenes:empleado_all' %}">EMPLEADOS</a>
                                            {% endif %}
                                        </li>
                                        <li class="nav-item">
                                            {% if request.user.is_authenticated %}
                                            <a class="nav-link text-white" href="{% url 'ordenes:comercio_all' %}">COMERCIOS</a>
                                            {% endif %}
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-white" href="{% url 'about' %}"">ABOUT</a>
                                        </li>
                                        {% if request.user.is_authenticated %}
                                        <li class="nav-item">
                                            <a class="nav-link text-white" href="{% url 'logout' %}">SALIR</a>
                                        </li>
                                        {% else%}
                                        <li class="nav-item">
                                            <a class="nav-link text-white" href="{% url 'login' %}">INGRESAR</a>
                                        </li>
                                        {% endif %}
                                        {% if request.user.is_authenticated %}
                                        <li class="nav-item">
                                            <a class="nav-link text-white" href="">{{ user.username | upper }}, Bienvenido</a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="p-3 mb-2 bg-info text-dark">
            <h5 id="footer">By Manuel Saquilán 2023</h5>
        </div>
    </footer>
    <script src="/static/js/main.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
        window.jQuery || document.write('<script src="http://mysite.com/jquery.min.js"><\/script>')
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

</body>

</html>

templates/base_impresion.html
{% load static %}
<!doctype html>
<html lang="es">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Reporte PDF</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <style>
        @page {
            size: 105mm 148mm ;
            margin: 0.5cm 0.5cm 0.5cm 0.5cm;
        }
        body {
            width: 10cm !important;
            height: 14.5cm;
            color: black;
            font-size: 60%;
            font-family: 'Roboto', sans-serif;
            line-height: .8;
            justify-content: baseline;
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: none; 
        }

        .titulo {
            line-height: 2pt;
            font-weight: bold;
        }
        .cuerpo{
            line-height: 1.1pt;
            
        }
    
        .pie {
            line-height: 2pt;
            font-weight: bold;
            font-size: large;
        }
        
        .validez .legales{
            font-style: oblique;
            list-style: 1.5pt;
        }
    </style>
</head>
<body>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
</body>
</html>